[BUILD-1061] - Favicon Tab Change
heynovaio/designstudio pull request #38
Opened 2024-09-23 21:49 UTC by FayeMao

2024-09-23 21:49 UTC, kirstenjvd commented
Task linked: [BUILD-1061 <Title> text change and Favicon](https://app.clickup.com/t/9009201449/BUILD-1061)

2024-09-23 23:50 UTC, FayeMao commented on src/images/favicon-32x32.png
This doesn't actually get added anywhere (that I know of)

2024-09-23 23:58 UTC, FayeMao commented on src/images/favicon-32x32.png
LOL jokes it does change the favicon

2024-09-24 14:29 UTC, kirstenjvd requested changes

2024-09-24 14:29 UTC, kirstenjvd commented on gatsby-config.js
Can you change this just to "Design Studio"  vs "dynamic to be Design Studio" - otherwise it looks great!

2024-09-24 17:00 UTC, merged